version: "3.9"

services:
  db_postgres:
    image: postgres
    environment:
      - POSTGRES_DB=apprefugio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: .
    environment:
      - DB_HOST=db_postgres
      - DB_NAME=apprefugio
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - .:/code
      - static:/code/static
      
    depends_on:
      - db_postgres
    
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app

volumes:
  .:
  postgres_data:
  static: